import { Application, Assets, Container, Sprite, Text, type Texture } from 'pixi.js';
import { loadBakedStructures } from './baked';
import type { StructureSprite } from './textures';

const CELL_WIDTH = 190;
const CELL_HEIGHT = 145;
const SHADOW_ALPHA = 0.45;

type Sample = { label: string; nativeScale: number; layers: { sprite: StructureSprite; alpha: number }[] };

async function run(): Promise<void> {
  if (!import.meta.env.DEV) throw new Error('The reference bench is development-only.');
  const baked = await loadBakedStructures();
  if (!baked) throw new Error('Missing baked atlas. Run npm run render && npm run pack.');

  const replacement = (variant: number, label: string): Sample => {
    const layers = (['shadow', 'body'] as const).map((layer) => {
      const sprite = baked.getExact('house', variant, layer);
      if (!sprite) throw new Error(`Missing house:${variant}:${layer}. Render the house study before opening the bench.`);
      sprite.texture.source.scaleMode = 'nearest';
      return { sprite, alpha: layer === 'shadow' ? SHADOW_ALPHA : 1 };
    });
    return { label, nativeScale: 0.5, layers };
  };

  const original = async (index: number, label: string): Promise<Sample> => {
    const texture = await Assets.load<Texture>(`/reference/sprites/Zeus_General/Zeus_Housing/${index}.png`);
    texture.source.scaleMode = 'nearest';
    return { label, nativeScale: 1, layers: [{ sprite: { texture, anchorX: 0.5, anchorY: 1 }, alpha: 1 }] };
  };

  const [hovel, homestead, turnedHomestead, tenement] = await Promise.all([
    original(785, 'Original · hovel'),
    original(787, 'Original · homestead'),
    original(788, 'Original · other orientation'),
    original(789, 'Original · tenement'),
  ]);
  const ours = replacement(6, 'Replacement · homestead');
  const turned = replacement(7, 'Replacement · mirrored');
  const study = replacement(14, 'New · courtyard extension');
  const studyName = new URLSearchParams(location.search).get('study') ?? 'ai-house';
  let generated: Sample | undefined;
  const generatedResolutions = new Map<number, Sample>();
  let highResolution = true;
  const response = await fetch(`/reference/studies/${studyName}.json`);
  if (response.ok && response.headers.get('content-type')?.includes('application/json')) {
    const metadata = await response.json();
    if (metadata.resolutions?.length !== 4) throw new Error('Re-run pipeline/prepare_study.py to prepare direct-source resolutions.');
    await Promise.all(metadata.resolutions.map(async (resolution: { scale: number; image: string }) => {
      const texture = await Assets.load<Texture>(`/reference/studies/${resolution.image}`);
      texture.source.scaleMode = 'nearest';
      generatedResolutions.set(resolution.scale, {
        label: `AI · ${studyName}`,
        nativeScale: 1 / resolution.scale,
        layers: [{ sprite: { texture, anchorX: metadata.anchorX, anchorY: metadata.anchorY }, alpha: 1 }],
      });
    }));
    generated = generatedResolutions.get(1);
    const provenance = metadata.model ? ` Generated by ${metadata.model} (${metadata.quality}).` : '';
    document.getElementById('study-note')!.textContent = `AI image ${studyName}: ${metadata.width}×${metadata.height}px at native size; proportions unchanged.${provenance} High-resolution mode samples the source directly at each display size; pixel-density mode enlarges the native image. Approximate ground alignment; supplied orientation only.`;
    document.body.dataset.aiStudy = 'true';
  } else {
    document.getElementById('study-note')!.textContent = `Optional AI study "${studyName}" not loaded. Generate one with pipeline/generate_study.py or pass ?study=<name>.`;
  }
  let zoom = 2;
  let mirror = false;
  let overlay = false;
  const app = new Application();
  await app.init({ width: 1140, height: 510, background: 0x3c3c3c, resolution: 1, antialias: false, autoStart: false });
  document.getElementById('bench')!.appendChild(app.canvas);

  const addSample = (sample: Sample, column: number, rowY: number, scale: number, alpha = 1): Container => {
    const container = new Container();
    const x = column * CELL_WIDTH * scale;
    for (const layer of sample.layers) {
      const sprite = new Sprite(layer.sprite.texture);
      sprite.anchor.set(layer.sprite.anchorX, layer.sprite.anchorY);
      sprite.position.set(x + CELL_WIDTH * scale / 2, rowY + (CELL_HEIGHT - 12) * scale);
      sprite.scale.set(scale * sample.nativeScale);
      sprite.roundPixels = true;
      sprite.alpha = layer.alpha * alpha;
      container.addChild(sprite);
    }
    app.stage.addChild(container);
    return container;
  };

  const label = (text: string, x: number, y: number): void => {
    const label = new Text({ text, style: { fontFamily: 'sans-serif', fontSize: 13, fill: 0xeee8dc } });
    label.position.set(x + 8, y + 8);
    app.stage.addChild(label);
  };

  const draw = (): void => {
    for (const child of app.stage.removeChildren()) child.destroy({ children: true });
    const columns = generated ? 6 : 5;
    const width = Math.max(CELL_WIDTH * columns, CELL_WIDTH * 3 * zoom);
    app.renderer.resize(width, CELL_HEIGHT * (zoom + 1) + 28);
    const selectedOriginal = mirror ? turnedHomestead : homestead;
    const selectedReplacement = mirror ? turned : ours;
    const strip = [hovel, selectedOriginal, selectedReplacement, study, tenement];
    if (generated) strip.splice(3, 0, generated);
    strip.forEach((sample, column) => {
      addSample(sample, column, 0, 1);
      label(sample.label, column * CELL_WIDTH, 0);
    });
    const rowY = CELL_HEIGHT + 28;
    addSample(selectedOriginal, 0, rowY, zoom);
    addSample(selectedReplacement, 1, rowY, zoom);
    if (overlay) addSample(selectedOriginal, 1, rowY, zoom, 0.5);
    let selectedStudy = generated ?? study;
    if (generated && highResolution) selectedStudy = generatedResolutions.get(zoom)!;
    addSample(selectedStudy, 2, rowY, zoom);
    if (generated && overlay) addSample(selectedOriginal, 2, rowY, zoom, 0.5);
    label(`Original · ${zoom}×`, 0, rowY);
    label(overlay ? 'Original at 50% over replacement' : `Replacement · ${zoom}×`, CELL_WIDTH * zoom, rowY);
    let studyLabel = `New design · ${zoom}× · not a gameplay tier`;
    if (generated) {
      const mode = highResolution ? 'direct source' : 'native pixels';
      studyLabel = `AI · ${zoom}× · ${mode}`;
      document.body.dataset.aiSampling = highResolution ? 'high-resolution' : 'pixel-density';
    }
    label(studyLabel, CELL_WIDTH * zoom * 2, rowY);
    app.render();
  };

  const controls = document.getElementById('controls')!;
  const sizes = document.createElement('select');
  sizes.setAttribute('aria-label', 'Enlargement');
  for (const scale of [1, 2, 3, 4]) sizes.add(new Option(`${scale}× enlargement`, String(scale), false, scale === zoom));
  sizes.onchange = () => { zoom = Number(sizes.value); draw(); };
  controls.appendChild(sizes);
  const button = (text: string, action: () => void): void => {
    const button = document.createElement('button');
    button.textContent = text;
    button.onclick = action;
    controls.appendChild(button);
  };
  button('Switch orientation', () => { mirror = !mirror; draw(); });
  button('Toggle overlay', () => { overlay = !overlay; draw(); });
  if (generated) {
    const sampling = document.createElement('select');
    sampling.setAttribute('aria-label', 'AI sampling');
    sampling.add(new Option('AI: High-resolution', 'high-resolution', true, true));
    sampling.add(new Option('AI: Original pixel density', 'pixel-density'));
    sampling.onchange = () => { highResolution = sampling.value === 'high-resolution'; draw(); };
    controls.appendChild(sampling);
  }
  draw();
  document.body.dataset.ready = 'true';
}

void run().catch((error: unknown) => {
  document.getElementById('error')!.textContent = `${String(error)}\nReferences must be extracted locally into reference/sprites; they are never bundled.`;
  document.body.dataset.error = 'true';
});
