import type { AppealBands } from './appeal';
import type { BuildingKind, Good, ServiceKind } from './types';

export interface BuildingDef {
  kind: BuildingKind;
  name: string;
  size: number;
  cost: number;
  colour: number;
  roofColour: number;
  height: number;
  workers: number;
  maxWalkers: number;
  appeal: AppealBands;
  requiresMeadow: boolean;
  needsRoad: boolean;
  produces: Good | null;
  consumes: Good | null;
  accepts: Good | null;
  supplies: Good | null;
  capacity: number;
  fireRisk: number;
  damageRisk: number;
  description: string;
}

const NO_APPEAL_GATE = Number.NEGATIVE_INFINITY;

export interface HouseTier {
  name: string;
  capacity: number;
  taxMultiplier: number;
  evolveAppeal: number;
  devolveAppeal: number;
  needs: ServiceKind[];
  appeal: AppealBands;
  colour: number;
  roofColour: number;
  height: number;
}

export const HOUSE_TIERS: HouseTier[] = [
  {
    name: 'Hut',
    capacity: 8,
    taxMultiplier: 1,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: [],
    appeal: { initial: -4, bandSize: 1, step: 1, range: 3 },
    colour: 0x9a8460,
    roofColour: 0x8d7440,
    height: 10,
  },
  {
    name: 'Shack',
    capacity: 16,
    taxMultiplier: 1,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: ['food'],
    appeal: { initial: -3, bandSize: 1, step: 1, range: 2 },
    colour: 0xa08868,
    roofColour: 0x9a7b45,
    height: 12,
  },
  {
    name: 'Hovel',
    capacity: 24,
    taxMultiplier: 1,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: ['food', 'water'],
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    colour: 0xbfa079,
    roofColour: 0x8d4f30,
    height: 15,
  },
  {
    name: 'Homestead',
    capacity: 32,
    taxMultiplier: 2,
    evolveAppeal: -12,
    devolveAppeal: -20,
    needs: ['food', 'water', 'culture'],
    appeal: { initial: -1, bandSize: 1, step: 0, range: 1 },
    colour: 0xd8c39a,
    roofColour: 0xa2492b,
    height: 19,
  },
  {
    name: 'Tenement',
    capacity: 40,
    taxMultiplier: 2,
    evolveAppeal: 0,
    devolveAppeal: -8,
    needs: ['food', 'water', 'culture'],
    appeal: { initial: 0, bandSize: 1, step: 0, range: 0 },
    colour: 0xeadcb8,
    roofColour: 0xb8502c,
    height: 24,
  },
  {
    name: 'Apartment',
    capacity: 48,
    taxMultiplier: 2,
    evolveAppeal: 8,
    devolveAppeal: 2,
    needs: ['food', 'water', 'oil', 'culture'],
    appeal: { initial: 1, bandSize: 1, step: 0, range: 1 },
    colour: 0xf1e6c6,
    roofColour: 0xc0562d,
    height: 30,
  },
  {
    name: 'Townhouse',
    capacity: 60,
    taxMultiplier: 3,
    evolveAppeal: 16,
    devolveAppeal: 8,
    needs: ['food', 'water', 'oil', 'culture'],
    appeal: { initial: 2, bandSize: 1, step: 1, range: 2 },
    colour: 0xf6eed6,
    roofColour: 0xc8642e,
    height: 36,
  },
];

export const BUILDINGS: Record<BuildingKind, BuildingDef> = {
  house: {
    kind: 'house',
    name: 'Housing',
    size: 2,
    cost: 10,
    colour: 0xc8a878,
    roofColour: 0x9c4b2f,
    height: 14,
    workers: 0,
    maxWalkers: 0,
    appeal: HOUSE_TIERS[0].appeal,
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 8,
    damageRisk: 5,
    description: 'Citizens settle here and evolve as their needs are met.',
  },
  wheatFarm: {
    kind: 'wheatFarm',
    name: 'Wheat Farm',
    size: 2,
    cost: 40,
    colour: 0xd8c56a,
    roofColour: 0x8a6b3a,
    height: 12,
    workers: 10,
    maxWalkers: 1,
    appeal: { initial: -3, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: true,
    needsRoad: true,
    produces: 'food',
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 4,
    fireRisk: 10,
    damageRisk: 4,
    description: 'Grows wheat on meadow. Cart pushers carry it to a granary.',
  },
  growersLodge: {
    kind: 'growersLodge',
    name: "Growers' Lodge",
    size: 2,
    cost: 25,
    colour: 0xcdbb84,
    roofColour: 0x7d6a3a,
    height: 14,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: true,
    needsRoad: true,
    produces: 'olives',
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 4,
    fireRisk: 10,
    damageRisk: 4,
    description: 'Tends an olive grove on meadow and carts the harvest to a press.',
  },
  olivePress: {
    kind: 'olivePress',
    name: 'Olive Press',
    size: 2,
    cost: 45,
    colour: 0xdccfae,
    roofColour: 0x8a6b3a,
    height: 17,
    workers: 12,
    maxWalkers: 0,
    appeal: { initial: -4, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    produces: 'oil',
    consumes: 'olives',
    accepts: 'olives',
    supplies: 'oil',
    capacity: 4,
    fireRisk: 14,
    damageRisk: 8,
    description: 'Presses olives into oil. Agora deliverymen collect the jars.',
  },
  granary: {
    kind: 'granary',
    name: 'Granary',
    size: 2,
    cost: 60,
    colour: 0xb8b0a0,
    roofColour: 0x6f6a5c,
    height: 20,
    workers: 18,
    maxWalkers: 0,
    appeal: { initial: -12, bandSize: 1, step: 2, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: 'food',
    supplies: 'food',
    capacity: 24,
    fireRisk: 6,
    damageRisk: 8,
    description: 'Holds the cartloads farms bring in. Agora deliverymen collect from here.',
  },
  agora: {
    kind: 'agora',
    name: 'Agora',
    size: 3,
    cost: 25,
    colour: 0xe3d6b4,
    roofColour: 0xb4623a,
    height: 16,
    workers: 12,
    maxWalkers: 3,
    appeal: { initial: 12, bandSize: 2, step: -2, range: 6 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 400,
    fireRisk: 8,
    damageRisk: 6,
    description: 'Deliverymen fetch food and oil; peddlers sell them house to house.',
  },
  college: {
    kind: 'college',
    name: 'College',
    size: 3,
    cost: 30,
    colour: 0xe6dcc0,
    roofColour: 0x7a6a4a,
    height: 20,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: -5, bandSize: 1, step: -3, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 6,
    damageRisk: 6,
    description: 'Trains philosophers and sends them to a podium to hold forth.',
  },
  podium: {
    kind: 'podium',
    name: 'Podium',
    size: 2,
    cost: 15,
    colour: 0xeee7d2,
    roofColour: 0xd8cdaa,
    height: 10,
    workers: 4,
    maxWalkers: 1,
    appeal: { initial: 3, bandSize: 1, step: -1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 3,
    description: 'A philosopher from a college speaks here, then walks the streets teaching.',
  },
  maintenanceOffice: {
    kind: 'maintenanceOffice',
    name: 'Maintenance Office',
    size: 2,
    cost: 10,
    colour: 0xc9bfa4,
    roofColour: 0x6e5a3c,
    height: 15,
    workers: 5,
    maxWalkers: 1,
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 4,
    description: 'Its superintendent keeps fire and collapse away from all he passes.',
  },
  fountain: {
    kind: 'fountain',
    name: 'Fountain',
    size: 1,
    cost: 25,
    colour: 0x8fbcd4,
    roofColour: 0xdfe9ef,
    height: 8,
    workers: 4,
    maxWalkers: 1,
    appeal: { initial: 4, bandSize: 2, step: -2, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 6,
    description: 'Sends water carriers along the roads.',
  },
  statue: {
    kind: 'statue',
    name: 'Statue',
    size: 1,
    cost: 30,
    colour: 0xe8e2d4,
    roofColour: 0xf6f2e8,
    height: 22,
    workers: 0,
    maxWalkers: 0,
    appeal: { initial: 8, bandSize: 1, step: -1, range: 3 },
    requiresMeadow: false,
    needsRoad: false,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 2,
    description: 'Beautifies the surrounding area.',
  },
  taxOffice: {
    kind: 'taxOffice',
    name: 'Tax Office',
    size: 2,
    cost: 25,
    colour: 0xcfc0a2,
    roofColour: 0x4f6f7a,
    height: 18,
    workers: 8,
    maxWalkers: 1,
    appeal: { initial: -4, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: false,
    needsRoad: true,
    produces: null,
    consumes: null,
    accepts: null,
    supplies: null,
    capacity: 0,
    fireRisk: 6,
    damageRisk: 5,
    description: 'Sends a clerk to collect tax from the houses he passes.',
  },
};

export const PLACEABLE: BuildingKind[] = [
  'house',
  'wheatFarm',
  'granary',
  'growersLodge',
  'olivePress',
  'agora',
  'college',
  'podium',
  'maintenanceOffice',
  'fountain',
  'taxOffice',
  'statue',
];

export const LABOUR_PRIORITY: BuildingKind[] = [
  'wheatFarm',
  'granary',
  'growersLodge',
  'olivePress',
  'agora',
  'maintenanceOffice',
  'college',
  'podium',
  'fountain',
  'taxOffice',
  'statue',
  'house',
];

export const UNITS_PER_CARTLOAD = 100;

export const ROAD_COST = 4;

export const ROADBLOCK_COST = 8;
