import type { AppealBands } from './appeal';
import { GODS, GOD_KINDS, type GodKind } from './gods';
import type { BuildingKind, Good, ServiceKind } from './types';

export interface BuildingDef {
  kind: BuildingKind;
  name: string;
  size: number;
  cost: number;
  colour: number;
  roofColour: number;
  height: number;
  workers: number;
  maxWalkers: number;
  appeal: AppealBands;
  requiresMeadow: boolean;
  needsRoad: boolean;
  requires: BuildingKind | null;
  minAppeal: number;
  needsNear?: 'woods' | 'rock';
  marbleCost?: number;
  produces: Good | null;
  consumes: Good | null;
  accepts: Good[];
  supplies: Good | null;
  capacity: number;
  fireRisk: number;
  damageRisk: number;
  description: string;
}

const NO_APPEAL_GATE = Number.NEGATIVE_INFINITY;

export interface HouseTier {
  name: string;
  capacity: number;
  taxMultiplier: number;
  evolveAppeal: number;
  devolveAppeal: number;
  needs: ServiceKind[];
  appeal: AppealBands;
  colour: number;
  roofColour: number;
  height: number;
}

export const HOUSE_TIERS: HouseTier[] = [
  {
    name: 'Hut',
    capacity: 8,
    taxMultiplier: 1,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: [],
    appeal: { initial: -4, bandSize: 1, step: 1, range: 3 },
    colour: 0x9a8460,
    roofColour: 0x8d7440,
    height: 10,
  },
  {
    name: 'Shack',
    capacity: 16,
    taxMultiplier: 1,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: ['food'],
    appeal: { initial: -3, bandSize: 1, step: 1, range: 2 },
    colour: 0xa08868,
    roofColour: 0x9a7b45,
    height: 12,
  },
  {
    name: 'Hovel',
    capacity: 24,
    taxMultiplier: 1,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: ['food', 'water', 'culture'],
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    colour: 0xbfa079,
    roofColour: 0x8d4f30,
    height: 15,
  },
  {
    name: 'Homestead',
    capacity: 32,
    taxMultiplier: 2,
    evolveAppeal: -12,
    devolveAppeal: -20,
    needs: ['food', 'water', 'culture', 'fleece'],
    appeal: { initial: -1, bandSize: 1, step: 0, range: 1 },
    colour: 0xd8c39a,
    roofColour: 0xa2492b,
    height: 19,
  },
  {
    name: 'Tenement',
    capacity: 40,
    taxMultiplier: 2,
    evolveAppeal: 0,
    devolveAppeal: -8,
    needs: ['food', 'water', 'culture', 'fleece', 'athletics'],
    appeal: { initial: 0, bandSize: 1, step: 0, range: 0 },
    colour: 0xeadcb8,
    roofColour: 0xb8502c,
    height: 24,
  },
  {
    name: 'Apartment',
    capacity: 48,
    taxMultiplier: 2,
    evolveAppeal: 8,
    devolveAppeal: 2,
    needs: ['food', 'water', 'oil', 'culture', 'fleece'],
    appeal: { initial: 1, bandSize: 1, step: 0, range: 1 },
    colour: 0xf1e6c6,
    roofColour: 0xc0562d,
    height: 30,
  },
  {
    name: 'Townhouse',
    capacity: 60,
    taxMultiplier: 3,
    evolveAppeal: 16,
    devolveAppeal: 8,
    needs: ['food', 'water', 'oil', 'culture', 'fleece', 'athletics', 'drama'],
    appeal: { initial: 2, bandSize: 1, step: 1, range: 2 },
    colour: 0xf6eed6,
    roofColour: 0xc8642e,
    height: 36,
  },
];


export const ELITE_TIERS: HouseTier[] = [
  {
    name: 'Residence',
    capacity: 6,
    taxMultiplier: 18,
    evolveAppeal: NO_APPEAL_GATE,
    devolveAppeal: NO_APPEAL_GATE,
    needs: ['food', 'water', 'oil', 'culture', 'fleece'],
    appeal: { initial: 10, bandSize: 2, step: -2, range: 6 },
    colour: 0xf0ead8,
    roofColour: 0xb8502c,
    height: 26,
  },
  {
    name: 'Mansion',
    capacity: 10,
    taxMultiplier: 18,
    evolveAppeal: 36,
    devolveAppeal: 25,
    needs: ['food', 'water', 'oil', 'culture', 'fleece', 'athletics'],
    appeal: { initial: 14, bandSize: 2, step: -2, range: 7 },
    colour: 0xf2ecdc,
    roofColour: 0xb8502c,
    height: 30,
  },
  {
    name: 'Manor',
    capacity: 16,
    taxMultiplier: 18,
    evolveAppeal: 50,
    devolveAppeal: 36,
    needs: ['food', 'water', 'oil', 'culture', 'fleece', 'wine', 'athletics', 'drama'],
    appeal: { initial: 18, bandSize: 2, step: -2, range: 8 },
    colour: 0xf6f1e2,
    roofColour: 0xc0603a,
    height: 34,
  },
  {
    name: 'Estate',
    capacity: 20,
    taxMultiplier: 18,
    evolveAppeal: 66,
    devolveAppeal: 50,
    needs: ['food', 'water', 'oil', 'culture', 'fleece', 'wine', 'athletics', 'drama'],
    appeal: { initial: 22, bandSize: 2, step: -2, range: 9 },
    colour: 0xfaf6ea,
    roofColour: 0xc0603a,
    height: 38,
  },
];

export const DWELLINGS: BuildingKind[] = ['house', 'estate'];

export function isDwelling(kind: BuildingKind): boolean {
  return DWELLINGS.includes(kind);
}

export function tiersOf(kind: BuildingKind): HouseTier[] {
  return kind === 'estate' ? ELITE_TIERS : HOUSE_TIERS;
}

export function tierOf(building: { kind: BuildingKind; tier: number }): HouseTier {
  return tiersOf(building.kind)[building.tier];
}


const SANCTUARY_COSTS: Record<GodKind, number> = {
  zeus: 620,
  poseidon: 540,
  demeter: 420,
  athena: 480,
  artemis: 400,
  apollo: 440,
  ares: 380,
  hephaestus: 380,
  aphrodite: 360,
  hermes: 340,
  dionysus: 320,
  hades: 460,
};

const SANCTUARY_ROOFS: Record<GodKind, number> = {
  zeus: 0xc8642e,
  poseidon: 0xa8552f,
  demeter: 0xb8502c,
  athena: 0xc45f34,
  artemis: 0xa85a30,
  apollo: 0xd0703a,
  ares: 0x9c3f28,
  hephaestus: 0x8f4526,
  aphrodite: 0xd07a4a,
  hermes: 0xc0603a,
  dionysus: 0xa04a3a,
  hades: 0x7c4030,
};

const SANCTUARY_MARBLE: Record<GodKind, number> = {
  zeus: 48,
  poseidon: 37,
  demeter: 27,
  athena: 24,
  artemis: 20,
  apollo: 20,
  ares: 13,
  hephaestus: 13,
  aphrodite: 11,
  hermes: 9,
  dionysus: 8,
  hades: 37,
};

const SANCTUARY_NAMES: Record<GodKind, string> = {
  zeus: 'Stronghold of Zeus',
  poseidon: 'Promontory of Poseidon',
  demeter: 'Garden of Demeter',
  athena: 'Arbor of Athena',
  artemis: "Artemis' Menagerie",
  apollo: 'Oracle of Apollo',
  ares: "Ares' Fortress",
  hephaestus: 'Forge of Hephaestus',
  aphrodite: "Aphrodite's Haven",
  hermes: "Hermes' Refuge",
  dionysus: 'Grove of Dionysus',
  hades: 'Gates of Hades',
};

type SanctuaryKind = Extract<BuildingKind, `sanctuary${string}`>;

export const SANCTUARY_KINDS: BuildingKind[] = GOD_KINDS.map((kind) => GODS[kind].sanctuary);

function sanctuaries(): Record<SanctuaryKind, BuildingDef> {
  return Object.fromEntries(
    GOD_KINDS.map((kind) => [
      GODS[kind].sanctuary,
      {
        kind: GODS[kind].sanctuary,
        name: SANCTUARY_NAMES[kind],
        size: 3,
        cost: SANCTUARY_COSTS[kind],
        colour: 0xefe9d8,
        roofColour: SANCTUARY_ROOFS[kind],
        height: 34,
        workers: 8,
        maxWalkers: 0,
        appeal: { initial: 14, bandSize: 2, step: -2, range: 6 },
        requiresMeadow: false,
        needsRoad: true,
        requires: null,
        minAppeal: 0,
        marbleCost: SANCTUARY_MARBLE[kind],
        produces: null,
        consumes: null,
        accepts: [],
        supplies: null,
        capacity: 0,
        fireRisk: 0,
        damageRisk: 2,
        description: `Kept for ${GODS[kind].name}, whose domain is ${GODS[kind].domain.toLowerCase()}. Tend it and the god takes an interest.`,
      } satisfies BuildingDef,
    ]),
  ) as unknown as Record<SanctuaryKind, BuildingDef>;
}

export const BUILDINGS: Record<BuildingKind, BuildingDef> = {
  house: {
    kind: 'house',
    name: 'Housing',
    size: 2,
    cost: 10,
    colour: 0xc8a878,
    roofColour: 0x9c4b2f,
    height: 14,
    workers: 0,
    maxWalkers: 0,
    appeal: HOUSE_TIERS[0].appeal,
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 8,
    damageRisk: 5,
    description: 'Citizens settle here and evolve as their needs are met.',
  },
  estate: {
    kind: 'estate',
    name: 'Residence',
    size: 4,
    cost: 200,
    colour: 0xf0ead8,
    roofColour: 0xb8502c,
    height: 26,
    workers: 0,
    maxWalkers: 0,
    appeal: ELITE_TIERS[0].appeal,
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 20,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 5,
    damageRisk: 4,
    description: 'A house for the wealthy, placed rather than grown. Nobles pay tax like no one else.',
  },
  wheatFarm: {
    kind: 'wheatFarm',
    name: 'Wheat Farm',
    size: 2,
    cost: 40,
    colour: 0xd8c56a,
    roofColour: 0x8a6b3a,
    height: 12,
    workers: 10,
    maxWalkers: 1,
    appeal: { initial: -3, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: true,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: 'food',
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 4,
    fireRisk: 10,
    damageRisk: 4,
    description: 'Grows wheat on meadow. Cart pushers carry it to a granary.',
  },
  growersLodge: {
    kind: 'growersLodge',
    name: "Growers' Lodge",
    size: 2,
    cost: 25,
    colour: 0xcdbb84,
    roofColour: 0x7d6a3a,
    height: 14,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: true,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: 'olives',
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 4,
    fireRisk: 10,
    damageRisk: 4,
    description: 'Tends an olive grove on meadow and carts the harvest to a press.',
  },
  timberMill: {
    kind: 'timberMill',
    name: 'Timber Mill',
    size: 2,
    cost: 35,
    colour: 0xc8ad82,
    roofColour: 0x8a6134,
    height: 18,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: -6, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    needsNear: 'woods',
    produces: 'wood',
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 5,
    fireRisk: 6,
    damageRisk: 4,
    description: 'Cuts timber from the woods around it. Must stand among trees.',
  },
  masonryShop: {
    kind: 'masonryShop',
    name: 'Masonry Shop',
    size: 2,
    cost: 75,
    colour: 0xd8d2c2,
    roofColour: 0x7c6a52,
    height: 18,
    workers: 15,
    maxWalkers: 1,
    appeal: { initial: -8, bandSize: 1, step: 1, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    needsNear: 'rock',
    produces: 'marble',
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 5,
    fireRisk: 2,
    damageRisk: 5,
    description: 'Cuts marble from an outcrop. Must stand beside rock.',
  },
  vineyard: {
    kind: 'vineyard',
    name: 'Vineyard',
    size: 2,
    cost: 25,
    colour: 0x9fae78,
    roofColour: 0x8a6134,
    height: 12,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: 1, bandSize: 1, step: -1, range: 2 },
    requiresMeadow: true,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: 'grapes',
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 5,
    fireRisk: 2,
    damageRisk: 4,
    description: 'Vines on the meadow. Its grapes go to a winery.',
  },
  winery: {
    kind: 'winery',
    name: 'Winery',
    size: 2,
    cost: 45,
    colour: 0xd8c8a4,
    roofColour: 0x8f4526,
    height: 20,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: 4, bandSize: 1, step: -1, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: 'wine',
    consumes: 'grapes',
    accepts: ['grapes'],
    supplies: null,
    capacity: 5,
    fireRisk: 4,
    damageRisk: 5,
    description: 'Presses grapes into wine. A city likes living near one.',
  },
  cardingShed: {
    kind: 'cardingShed',
    name: 'Carding Shed',
    size: 2,
    cost: 16,
    colour: 0xd0c4a2,
    roofColour: 0x9a7b45,
    height: 14,
    workers: 8,
    maxWalkers: 1,
    appeal: { initial: -4, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: true,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: 'fleece',
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 5,
    fireRisk: 3,
    damageRisk: 4,
    description: 'Eight sheep on the meadow, and the fleece a homestead needs.',
  },
  olivePress: {
    kind: 'olivePress',
    name: 'Olive Press',
    size: 2,
    cost: 45,
    colour: 0xdccfae,
    roofColour: 0x8a6b3a,
    height: 17,
    workers: 12,
    maxWalkers: 0,
    appeal: { initial: -4, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: 'oil',
    consumes: 'olives',
    accepts: ['olives'],
    supplies: 'oil',
    capacity: 4,
    fireRisk: 14,
    damageRisk: 8,
    description: 'Presses olives into oil. Agora deliverymen collect the jars.',
  },
  granary: {
    kind: 'granary',
    name: 'Granary',
    size: 2,
    cost: 60,
    colour: 0xb8b0a0,
    roofColour: 0x6f6a5c,
    height: 20,
    workers: 18,
    maxWalkers: 0,
    appeal: { initial: -12, bandSize: 1, step: 2, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: ['food'],
    supplies: 'food',
    capacity: 24,
    fireRisk: 6,
    damageRisk: 8,
    description: 'Holds the cartloads farms bring in. Agora deliverymen collect from here.',
  },
  agora: {
    kind: 'agora',
    name: 'Agora',
    size: 3,
    cost: 25,
    colour: 0xe3d6b4,
    roofColour: 0xb4623a,
    height: 16,
    workers: 12,
    maxWalkers: 3,
    appeal: { initial: 12, bandSize: 2, step: -2, range: 6 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 400,
    fireRisk: 8,
    damageRisk: 6,
    description: 'Deliverymen fetch food and oil; peddlers sell them house to house.',
  },
  college: {
    kind: 'college',
    name: 'College',
    size: 3,
    cost: 30,
    colour: 0xe6dcc0,
    roofColour: 0x7a6a4a,
    height: 20,
    workers: 12,
    maxWalkers: 1,
    appeal: { initial: -5, bandSize: 1, step: -3, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 6,
    damageRisk: 6,
    description: 'Trains philosophers and sends them to a podium to hold forth.',
  },
  podium: {
    kind: 'podium',
    name: 'Podium',
    size: 2,
    cost: 15,
    colour: 0xeee7d2,
    roofColour: 0xd8cdaa,
    height: 10,
    workers: 4,
    maxWalkers: 1,
    appeal: { initial: 3, bandSize: 1, step: -1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 3,
    description: 'A philosopher from a college speaks here, then walks the streets teaching.',
  },
  gymnasium: {
    kind: 'gymnasium',
    name: 'Gymnasium',
    size: 3,
    cost: 30,
    colour: 0xf0ead6,
    roofColour: 0xb8502c,
    height: 22,
    workers: 7,
    maxWalkers: 1,
    appeal: { initial: 6, bandSize: 2, step: -2, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 3,
    description: 'Sends an athlete along the roads. Houses he passes are counted athletic.',
  },
  dramaSchool: {
    kind: 'dramaSchool',
    name: 'Drama School',
    size: 3,
    cost: 16,
    colour: 0xeee7d2,
    roofColour: 0xc0603a,
    height: 20,
    workers: 10,
    maxWalkers: 1,
    appeal: { initial: 2, bandSize: 1, step: -1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 2,
    damageRisk: 3,
    description: 'Trains actors and sends them to a theatre to perform.',
  },
  theatre: {
    kind: 'theatre',
    name: 'Theatre',
    size: 4,
    cost: 60,
    colour: 0xf4eedc,
    roofColour: 0xb8502c,
    height: 28,
    workers: 18,
    maxWalkers: 1,
    appeal: { initial: 10, bandSize: 2, step: -2, range: 6 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 3,
    description: 'An actor performs here, then walks the streets. Nothing pleases a city more.',
  },
  stadium: {
    kind: 'stadium',
    name: 'Stadium',
    size: 5,
    cost: 200,
    colour: 0xf6f1e2,
    roofColour: 0xc0603a,
    height: 30,
    workers: 45,
    maxWalkers: 0,
    appeal: { initial: 16, bandSize: 2, step: -2, range: 8 },
    requiresMeadow: false,
    needsRoad: true,
    requires: 'palace',
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 2,
    description: 'Games are held here. Every house in the city is the better for it.',
  },
  maintenanceOffice: {
    kind: 'maintenanceOffice',
    name: 'Maintenance Office',
    size: 2,
    cost: 10,
    colour: 0xc9bfa4,
    roofColour: 0x6e5a3c,
    height: 15,
    workers: 5,
    maxWalkers: 1,
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 4,
    description: 'Its superintendent keeps fire and collapse away from all he passes.',
  },
  fountain: {
    kind: 'fountain',
    name: 'Fountain',
    size: 1,
    cost: 25,
    colour: 0x8fbcd4,
    roofColour: 0xdfe9ef,
    height: 8,
    workers: 4,
    maxWalkers: 1,
    appeal: { initial: 4, bandSize: 2, step: -2, range: 4 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 6,
    description: 'Sends water carriers along the roads.',
  },
  statue: {
    kind: 'statue',
    name: 'Statue',
    size: 1,
    cost: 30,
    colour: 0xe8e2d4,
    roofColour: 0xf6f2e8,
    height: 22,
    workers: 0,
    maxWalkers: 0,
    appeal: { initial: 8, bandSize: 1, step: -1, range: 3 },
    requiresMeadow: false,
    needsRoad: false,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 2,
    description: 'Beautifies the surrounding area.',
  },
  taxOffice: {
    kind: 'taxOffice',
    name: 'Tax Office',
    size: 2,
    cost: 25,
    colour: 0xcfc0a2,
    roofColour: 0x4f6f7a,
    height: 18,
    workers: 8,
    maxWalkers: 1,
    appeal: { initial: -4, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: false,
    needsRoad: true,
    requires: 'palace',
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 6,
    damageRisk: 5,
    description: 'Sends a clerk to collect tax from the houses he passes.',
  },
  palace: {
    kind: 'palace',
    name: 'Palace',
    size: 4,
    cost: 125,
    colour: 0xf2ecdc,
    roofColour: 0xb8502c,
    height: 40,
    workers: 0,
    maxWalkers: 0,
    appeal: { initial: 18, bandSize: 3, step: -3, range: 6 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 2,
    description: 'The seat of your rule. Nothing that governs the city may be built until it stands.',
  },
  tradingPost: {
    kind: 'tradingPost',
    name: 'Trading Post',
    size: 2,
    cost: 90,
    colour: 0xd8c8a4,
    roofColour: 0xb8502c,
    height: 20,
    workers: 12,
    maxWalkers: 0,
    appeal: { initial: -6, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: ['oil', 'wine', 'fleece', 'wood', 'marble'],
    supplies: 'food',
    capacity: 20,
    fireRisk: 4,
    damageRisk: 6,
    description: 'Oil carted here leaves for other cities, and bought grain arrives here for the agora.',
  },
  infirmary: {
    kind: 'infirmary',
    name: 'Infirmary',
    size: 3,
    cost: 35,
    colour: 0xf0ece0,
    roofColour: 0xb8502c,
    height: 22,
    workers: 11,
    maxWalkers: 1,
    appeal: { initial: 2, bandSize: 1, step: -1, range: 2 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 4,
    description: 'Sends a doctor along the roads. Houses he passes keep their health.',
  },
  watchpost: {
    kind: 'watchpost',
    name: 'Watchpost',
    size: 2,
    cost: 20,
    colour: 0xd8cdb4,
    roofColour: 0x8f4526,
    height: 24,
    workers: 6,
    maxWalkers: 1,
    appeal: { initial: -2, bandSize: 1, step: 1, range: 2 },
    requiresMeadow: false,
    needsRoad: true,
    requires: null,
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 3,
    description: 'Sends a watchman on his rounds. Where he walks, no one turns to crime.',
  },
  tower: {
    kind: 'tower',
    name: 'Tower',
    size: 2,
    cost: 50,
    colour: 0xe4dcc4,
    roofColour: 0x8f4526,
    height: 44,
    workers: 15,
    maxWalkers: 0,
    appeal: { initial: -4, bandSize: 1, step: 1, range: 3 },
    requiresMeadow: false,
    needsRoad: true,
    requires: 'palace',
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 3,
    description: 'Archers hold the wall from here. A tower is worth companies when the city is attacked.',
  },
  monument: {
    kind: 'monument',
    name: 'Monument',
    size: 3,
    cost: 300,
    colour: 0xf6f1e2,
    roofColour: 0xd8c06a,
    height: 46,
    workers: 0,
    maxWalkers: 0,
    appeal: { initial: 20, bandSize: 2, step: -2, range: 9 },
    requiresMeadow: false,
    needsRoad: false,
    requires: null,
    minAppeal: 0,
    marbleCost: 30,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 1,
    description: 'Raised to a quest fulfilled. Nothing in the city is admired more.',
  },
  heroHall: {
    kind: 'heroHall',
    name: 'Hero Hall',
    size: 4,
    cost: 240,
    colour: 0xf2ecdc,
    roofColour: 0xb8502c,
    height: 32,
    workers: 10,
    maxWalkers: 0,
    appeal: { initial: 15, bandSize: 2, step: -2, range: 7 },
    requiresMeadow: false,
    needsRoad: true,
    requires: 'palace',
    minAppeal: 0,
    produces: null,
    consumes: null,
    accepts: [],
    supplies: null,
    capacity: 0,
    fireRisk: 0,
    damageRisk: 2,
    description: 'A hall kept ready for a hero. Meet what he asks of the city and he will come.',
  },
  ...sanctuaries(),
};

export const PLACEABLE: BuildingKind[] = [
  'house',
  'estate',
  'wheatFarm',
  'granary',
  'growersLodge',
  'olivePress',
  'timberMill',
  'masonryShop',
  'vineyard',
  'winery',
  'cardingShed',
  'agora',
  'college',
  'podium',
  'gymnasium',
  'dramaSchool',
  'theatre',
  'stadium',
  'maintenanceOffice',
  'infirmary',
  'watchpost',
  'fountain',
  'palace',
  'taxOffice',
  'tradingPost',
  'statue',
  ...SANCTUARY_KINDS,
  'heroHall',
  'monument',
  'tower',
];

export const LABOUR_PRIORITY: BuildingKind[] = [
  'wheatFarm',
  'granary',
  'growersLodge',
  'olivePress',
  'timberMill',
  'masonryShop',
  'vineyard',
  'winery',
  'cardingShed',
  'agora',
  'tradingPost',
  'maintenanceOffice',
  'infirmary',
  'watchpost',
  'college',
  'podium',
  'fountain',
  'taxOffice',
  'statue',
  ...SANCTUARY_KINDS,
  'heroHall',
  'monument',
  'tower',
  'house',
  'estate',
];

export const UNITS_PER_CARTLOAD = 100;

export const ROAD_COST = 4;

export const ROADBLOCK_COST = 8;

export const WALL_COST = 6;
